// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUserEmail.sql

package database

import (
	"context"
)

const getUsrEmail = `-- name: GetUsrEmail :one
Select id, created_at, updated_at, email, hashed_password from users 
WHERE email = $1
`

func (q *Queries) GetUsrEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsrEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
