// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refreshToken.sql

package database

import (
	"context"
	"database/sql"
)

const refreshToken = `-- name: RefreshToken :exec
UPDATE refresh_tokens
SET expires_at = $1
where token = $2
`

type RefreshTokenParams struct {
	ExpiresAt sql.NullTime
	Token     string
}

func (q *Queries) RefreshToken(ctx context.Context, arg RefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, refreshToken, arg.ExpiresAt, arg.Token)
	return err
}
